name: jellyflut
description: Jellyfin client made with Flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.5.1

environment:
  sdk: ">=2.17.0 <3.0.0"

module:
  androidX: true

dependencies:
  animations: ^2.0.3
  archive: ^3.3.0
  audio_video_progress_bar: ^0.10.0
  auto_route: ^4.0.1
  better_player: ^0.0.83
  bloc: ^8.0.3
  blurhash_dart: ^1.1.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  community_material_icon: ^5.9.55
  cupertino_icons: ^1.0.5
  dart_vlc: ^0.2.1
  device_info_plus: ^3.2.3
  dio: ^4.0.6
  drop_shadow: ^0.0.1+4
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.0
  equatable: ^2.0.3
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_colorpicker: ^1.0.3
  flutter_native_splash: ^2.2.3
  flutter_settings_ui: ^2.0.1
  flutter_svg: ^0.23.0+1
  flutter_vlc_player: ^7.1.5
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  just_audio: ^0.9.24
  just_audio_libwinmedia: ^0.0.4
  drift: ^1.6.0
  octo_image: ^1.0.2
  package_info_plus: ^1.4.2
  path: ^1.8.1
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  photo_view: ^0.14.0
  provider: ^6.0.3
  reactive_forms: ^13.0.0
  responsive_builder: ^0.4.2
  rxdart: ^0.27.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  shu_epub:
    git:
      url: https://github.com/getBoolean/shu_epub.git
      ref: main
  sqlite3_flutter_libs: ^0.5.7
  subtitle: ^0.1.0-beta.3
  url_launcher: ^6.1.2
  universal_io: ^2.0.4
  uuid: ^3.0.6
  video_player: ^2.4.4
  wakelock: ^0.6.1+2
  window_manager: ^0.2.5
  youtube_explode_dart: ^1.11.0

dependency_overrides: 
  xml: ^5.3.1
  universal_html:
    git:
      url: https://github.com/juancastillo0/universal_html.git
      ref: 5a079ea

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_web_compilers: ^3.2.3
  drift_dev: ^1.6.0
  build_runner: ^2.1.10
  dart_code_metrics: ^4.15.2
  icons_launcher: ^1.1.9
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - img/
    - translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Regular.ttf
          style: normal
    - family: HindMadurai
      fonts:
        - asset: fonts/HindMadurai-Regular.ttf
          style: normal
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
          style: normal

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
