name: database_downloads_api
description: A Flutter implementation of the DownloadApi that uses local sqlite.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  downloads_api:
    path: ../downloads_api
  jellyflut_models:
    path: ../../jellyflut_models
  sqlite_database:
    path: ../../sqlite_database
  json_annotation: ^4.5.0
  meta: ^1.7.0
  rxdart: ^0.27.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
