name: jellyflut_models
description: All models that app needs
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  device_info_plus: ^4.0.0
  drift: ^1.7.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  http: ^0.13.4
  json_annotation: ^4.5.0
  meta: ^1.7.0
  path_provider: ^2.0.11
  rxdart: ^0.27.4
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  drift_dev: ^1.7.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.21.0
  very_good_analysis: ^3.0.1
